# Generated by Django 3.2.13 on 2022-07-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_contact_somethineelse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='something',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='somethineelse',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
