# Generated by Django 3.2.13 on 2022-07-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20220704_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='post',
        ),
    ]
