# Generated by Django 3.2.13 on 2022-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='h', max_length=250),
        ),
    ]
